### ISSUE TITLE
consulta

### ISSUE THREAD

**Issue by CarolinaDiJulio** [CarolinaDiJulio/practica_dwec_gestor_presupuesto#1]
Hola Pedro, ayer por la noche elimine todo porque creí que no pasaban los test de JS I.
me aparece asi
![Sin título](https://github.com/user-attachments/assets/d12794a6-e3f6-44e1-b4e5-0d4e6a0da7d6)

Eso es que ha pasado los test?  Hay uno que me aparece en rojo y no entiendo porqué.
No sé si lo de la introduccion tambien habia que hacerlo pero yo lo subí.

Otra consulta: con respecto a los parametros del objeto gasto:
entiendo que el parametro descripcion, es por defecto de tipo string
pero al parametro valor, tengo que ponerle Number(valor) para que el valor que guarde sea tipo numerico?
Gracias @pedroprieto

**Comment by pedroprieto** [comment]
Buenas, @CarolinaDiJulio ,

No tienes que eliminar todo: simplemente añadir más cambios. Cada vez que se añaden cambios, se ejecutan de nuevo los tests. No hay que borrar nada, simplemente seguir haciendo commits.

En tu caso, se pasa un test, pero el segundo falla. Cada práctica (la I, en ese caso) tiene varios tests. Así puedes ir comprobando tu avance.

En cuanto a los parámetros, en JavaScript las variables no tienen tipo: almacenan el dato que les pases. Por tanto, tienes que asumir que el parámetro `descripcion` puede ser de cualquier tipo. Para forzar que sea un número, efectivamente tienes que convertirlo a `Number`. Lo que ocurre, es que `Number("hola")`, por ejemplo, te devolverá `NaN` (*Not a Number*). Por ello, tienes que controlar con un `if`o similar si el dato que le entra es un número o no. En el vídeo de la grabación de la tutoría de este miércoles, al final, lo explico con un ejemplo.

Ánimo y un saludo!!

**Comment by CarolinaDiJulio** [comment]
@pedroprieto  Pero no entiendo cual es el test que no paso, porque cuando hago no run test1 pasan todos.. Pero aquí me marca que ese no pasa

**Comment by pedroprieto** [comment]
Sí, el test 1 pasa. Lo que ocurre es que hay 8 tests, que iremos haciendo durante 8 semanas. Para esta solo tienes que pasar el 1 y el 2. Y el 1 lo pasas:
![imagen](https://github.com/user-attachments/assets/af17951b-7625-463d-8fc4-0768e94ac8c5)

El segundo, que se ejecuta con `npm run test2`, no lo pasas aún.

**Comment by CarolinaDiJulio** [comment]
Ah vale, ya entiendo. Me confundía que "presentación no de" tenga una cruz. Perdona los mil mensajes 😅
Muchas gracias

**Comment by pedroprieto** [comment]
Sin problema :blush: Ánimo!!! :muscle:
