### ISSUE TITLE
Consulta JS III

### ISSUE THREAD

**Issue by CarolinaDiJulio** [CarolinaDiJulio/practica_dwec_gestor_presupuesto#2]
Hola @pedroprieto
Tengo una consulta sobre el metodo Obtener periodo de agrupación.
la fecha esta correcta pero no pasa el test porque en lugar de devolver "2021-09" devuelvo "2021-9"
¿Tengo que cambiar algo del formato de la fecha?
Sino, la "opcion" que se me ocurre es poner un if en el que a todas las fechas menores a 10 se les añada un 0, pero no creo que sea muy correcto

**Comment by CarolinaDiJulio** [comment]
En la funcion filtrar gastos, se debe usar la funcion filter o toda la funcion debe ser filter? tengo que hacer una funcion constructora para el onjeto con las propiedades fechaDesde, fechaHasta... etc?
@pedroprieto

**Comment by pedroprieto** [comment]
> Hola @pedroprieto Tengo una consulta sobre el metodo Obtener periodo de agrupación. la fecha esta correcta pero no pasa el test porque en lugar de devolver "2021-09" devuelvo "2021-9" ¿Tengo que cambiar algo del formato de la fecha? Sino, la "opcion" que se me ocurre es poner un if en el que a todas las fechas menores a 10 se les añada un 0, pero no creo que sea muy correcto

Es una opción, aunque poco "elegante", podríamos decir :wink:

Tienes otra opción: pasa la fecha a `string` con `toISOString()` y quédate con un trozo utilizando `substr` para recortarlo. Por ejemplo:
```js
let anyomes = fecha.toISOString().substr(0,7)
```

**Comment by pedroprieto** [comment]
> En la funcion filtrar gastos, se debe usar la funcion filter o toda la funcion debe ser filter? tengo que hacer una funcion constructora para el onjeto con las propiedades fechaDesde, fechaHasta... etc? @pedroprieto

Tienes que llamar una única vez a `filter`. Dentro de su callback, realizar todos los filtrados que se piden.

`fechaDesde`, `fechaHasta` y demás, son parámetros de `filtrarGastos`. `filtrarGastos` no está definida dentro del objeto, no es un método: es una función independiente.

**Comment by CarolinaDiJulio** [comment]
Si, se que filtrarGastos es una función independiente. Pero se indica que tiene un solo parámetro que es un objeto {}, fechaDesde, fechaHasta y demás no pasan como parámetros sino que son propiedades de un objeto no?

**Comment by pedroprieto** [comment]
Ah, perdona, te entendí mal. Y lo expliqué mal también, efectivamente :cold_sweat: 

La función tendrá un único parámetro, que será un objeto. No tienes que crear ningún constructor para ese objeto: tan solo asumir dentro de la función que el parámetro tendrá esas propiedades, `fechaDesde`, etcétera. Ten en cuenta que la función no tiene que crear el objeto: tan solo usarlo; el objeto se pasa desde fuera, al ejecutar la función.

**Comment by CarolinaDiJulio** [comment]
Estoy teniendo problemas con la funcion de filtrarGastos, me dice todo el tiempo que fechaDesde o fechaHasta no funcionan correctamente, de hecho cuando realizo el test el valor esperado es 4 y el actual 3, modifico para saber si es por un <= o < y me dice que el valor esperado es 3 y el valor actual es 4!
Será por la forma en que convierto las fechas?@pedroprieto

**Comment by pedroprieto** [comment]
Buenas,

Sube los cambios para que pueda echarles un vistazo: si no, no puedo ayudarte. Avísame cuando lo tengas.

**Comment by CarolinaDiJulio** [comment]
Buenas, lo he solucionado lo de la funcion FiltrarGastos. Ahora me he quedado en Agrupar gastos.
Hice un push para que puedas hecharle un vistazo al codigo, pasa los dos primeros test pero el de agrupar gastos me dice:
La opción de agrupar y filtrar por etiquetas no funciona
      + expected - actual

      -3
      +2
   @pedroprieto

**Comment by CarolinaDiJulio** [comment]
Lo he podido solucionar, el problema es que estaba creando el objeto con la propiedad etiquetas, y no etiquetasTiene
