### ISSUE TITLE
JS interaccion con HTML

### ISSUE THREAD

**Issue by CarolinaDiJulio** [CarolinaDiJulio/practica_dwec_gestor_presupuesto#3]
Hola @pedroprieto
Hice un push, para consultarte si esta bien lo que hice en la funcion mostrarDatoEnId, porque no pasa el test pero no se que es lo que estoy haciendo mal, exporte las funciones y tambien realice el import en el otro archivo y enlace el script al html

**Comment by CarolinaDiJulio** [comment]
solucionado

**Comment by CarolinaDiJulio** [comment]
@pedroprieto
Hice un push nuevamente, porque la funcion mostrarGastoWeb, pasa el test pero en el html me muestra todas las etiquetas en un solo gasto 
![image](https://github.com/user-attachments/assets/bc911ee1-f90e-4c10-b4db-85c60101b614)

**Comment by pedroprieto** [comment]
Buenas,

El problema está aquí:
https://github.com/CarolinaDiJulio/practica_dwec_gestor_presupuesto/blob/22f3af8eb3b3b2e7e58b2178e1dc5cbd4a954c0a/js/gestionPresupuestoWeb.js#L21

Buscas el primer elemento con ese nombre de clase. Dicho elemento corresponde al primer gasto, por lo que todas las etiquetas se ponen ahí.

En su lugar, en lugar de añadir las etiquetas así:
https://github.com/CarolinaDiJulio/practica_dwec_gestor_presupuesto/blob/22f3af8eb3b3b2e7e58b2178e1dc5cbd4a954c0a/js/gestionPresupuestoWeb.js#L27

Añádelas al elemento `nuevoGasto`, creado anteriormente:
https://github.com/CarolinaDiJulio/practica_dwec_gestor_presupuesto/blob/22f3af8eb3b3b2e7e58b2178e1dc5cbd4a954c0a/js/gestionPresupuestoWeb.js#L7
```js
 nuevoGasto.appendChild(nuevaEtiqueta) 
```

Un saludo!

**Comment by pedroprieto** [comment]
Buenas de nuevo, @CarolinaDiJulio 

He visto en tu entrega que lo has resuelto poniendo `querySelector` sobre el elemento `nuevoGasto`. Bien hecho. En mi explicación te decía que las añadieras sobre `nuevoGasto`, lo que no era correcto: debías buscar el elemento contenedor de las etiquetas dentro de `nuevoGasto` y añadirlas ahí, tal como has hecho.

Si en lugar de utilizar `innerHTML` hubieras utilizado el DOM para crear nodos, habrías tenido la referencia del elemento correspondiente en código.

En cualquier caso, bien hecho!! :muscle:

**Comment by CarolinaDiJulio** [comment]
Hola @pedroprieto ! si, de esa manera siento que voy "paso a paso" y puedo visualizar todo mejor en mi cabeza, un problema que había tenido es que intentaba acceder con querySelector despues de haber creado el nuevoGasto pero sin haber realizado el appendChild (elemento.appendChild(nuevoGasto)) entonces se generaba un error porque no lo encontraba :sweat_smile:

Otro problema que me surgió fue que cuando realizaba los test con npm run test4 pasaban todos OK, pero al subirlos a github no pasaba el test de interaccion con HTML pero me di cuenta rápido que era por la forma en que se visualizaba la fecha (estaba como timestamp) quizas a algun compañero le ocurre lo mismo

**Comment by pedroprieto** [comment]
En principio, los errores que se generan en GitHub pero no en equipo local son debidos a que, al utilizar `toISOString()`, se incluye el idioma, `toISOString('es')`. El test no incluye el idioma: por tanto, en GitHub, al estar el servidor en inglés, muestra la fecha de manera incorrecta. No sé si es eso lo que te habrá pasado...

En cualquier caso, bien resuelto todo!! :clap:
